name: CI Pipeline

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Force clean installation
      run: |
        # Видалити будь-який існуючий lock-файл
        rm -f package-lock.json
        # Встановити залежності без використання ci
        npm install --no-package-lock
        npm install

    - name: Run tests
      run: npm test -- --watchAll=false

  build:
    name: Build Next.js App
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Force clean installation
      run: |
        rm -f package-lock.json
        npm install --no-package-lock
        npm install

    - name: Build application
      run: npm run build